# vim:et:sw=2:

nick: jabbot

cored:
  listen: http://127.0.0.1:18000

memoryd:
  listen: http://127.0.0.1:18002
  database_root: /tmp/jabbot/memory

telegram:
  listen: http://127.0.0.1:18010
  poll_interval: 15

ircbot:
  listen: http://127.0.0.1:18011
  networks:
    'libera.chat':
      nick: jabbot
      server: irc.libera.chat
      port: 6697
      tls: yes
      channels:
        - '##jabbot'

xmpp:
  accounts: {}
    # google-talk-account@gmail.com: 
    #   - password-here
    #   - talk.google.com
    #   - 5223
    #   - { domain: gmail.com, old_style_ssl: 1 }

plugins: []
  # - CPANAuthors
  # - URLPreview
  # - en_us::Facts
  # - en_us::Eliza
  # - zh_tw::RandomChatbot
  # - zh_tw::Thsrc
  # - zh_tw::Polite
  # - Math
  # - zh_tw::TaiwanLotto
  # - zh_tw::DateDay
 
feeds:
  jabbot-commits:
    type: atom
    url:  http://github.com/feeds/gugod/commits/jabbot/master
    showAuthor: true
    appendurl: true
    shorturl: true
    publish_to:
      - "libera.chat:##jabbot"

cpantw:
  publish_to:
    - "libera.chat:##jabbot"

twitter:
  username:
  password:
  track: "#perl,#jabbot"
  publish_to:
    - "libera.chat:##jabbot"

plurk:
  listen: http://localhost:18020/
  username: ''
  password: ''
  access_token: ''
  access_token_secret: ''
  consumer_key: ''
  consumer_secret: ''
